# Generated by Django 5.0.6 on 2025-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cafe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetbooking',
            name='price_per_visitor',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
