# Generated by Django 5.0.6 on 2025-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_banquetbooking_price_per_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetbooking',
            name='client_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AddField(
            model_name='banquetbooking',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название мероприятия'),
        ),
        migrations.AddField(
            model_name='banquetbooking',
            name='event_status',
            field=models.CharField(choices=[('confirmed', 'Подтверждено'), ('not_confirmed', 'Не подтверждено')], default='not_confirmed', max_length=20, verbose_name='Статус мероприятия'),
        ),
    ]
