# Generated by Django 5.0.6 on 2025-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_banquetbooking_client_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetbooking',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentConfirmationCode',
        ),
    ]
