# Generated by Django 5.0.6 on 2025-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_banquetbooking_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetbooking',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='organization_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
