# Generated by Django 5.0.6 on 2025-05-13 18:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_banquetbooking_client_email_cafe_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='organization_id',
            field=models.CharField(default=accounts.models.generate_organization_id, max_length=20, unique=True),
        ),
    ]
