# Generated by Django 5.0.6 on 2025-05-13 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_cafe_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='accounts.cafe'),
        ),
    ]
